[package]
name = "amafatt"
version = "1.0.1"
authors = ["Luciano Bestia <luciano.bestia@gmail.com>"]
edition = "2018"
description="processa la txt di amazon e chiama la api di FattureInCloud.it"
repository = "https://github.com/LucianoBestia/amafatt"
readme = "README.md"
license = "MIT"
keywords = ["wasm","dodrio","virtual dom"]
categories = ["amazon","fattureincloud"]

[lib]
crate-type = ["cdylib"]

[profile.release]
#smaller wasm size
lto = true
#optimize for size 's', more opt for size 'z'
opt-level = 'z'

[dependencies]
wasm-bindgen = { version = "0.2.47", features = ["serde-serialize"] }
js-sys = "0.3"
unwrap = "1.2.1"
dodrio = "0.1.0"
console_error_panic_hook = "0.1.6"
serde = { version = "1.0.94", features = ["derive"] }
serde_derive = "1.0.94"
serde_json = "1.0"
futures = "0.1.26"
wasm-bindgen-futures = "0.3.24"
log = "0.4.6"
typed-html = {version="0.2.1", features = ["dodrio_macro"]}
csv = "1"

[dependencies.web-sys]
version = "0.3.24"
features = [
  "console",
  "Document",
  "Element",
  "HtmlElement",
  "HtmlInputElement",
  "HtmlTextAreaElement",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Storage",
  "Window",
]

