# mem4_game/mem4/Makefile.toml
# https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo build development"
    clear = true
    dependencies = [
		"insert-readme",
        "build-dev",
        "post-build",
    ]

    [tasks.release]
    description = "cargo build release"
    clear = true
    dependencies = [
		"insert-readme",
        "build-release",
        "post-build",
    ]

    [tasks.doc]
    description = "create docs from comments"
    clear = true
    dependencies = [
		"insert-readme",
        "cargo-doc",
		"doc-copy",
    ]
# endregion


[tasks.build-dev]
clear = true
private = true
description = "build wasm in dev mode"
command = "wasm-pack"
args = ["build", "--target", "web","--dev"]

[tasks.build-release]
clear = true
private = true
description = "build wasm in release mode"
command = "wasm-pack"
args = ["build","--target", "web","--release"]

[tasks.post-build]
clear = true
private = true
description = "different task for windows or linux"
windows_alias = "windows_post-build"

[tasks.windows_post-build]
clear = true
private = true
description = "open browser and start http server"
script = [
    "start chrome http://127.0.0.1:8086", 
    #"start \"firefox\" \"C:\\Program Files\\Mozilla Firefox\\firefox.exe\" 127.0.0.1:8086",
    "basic-http-server -a 127.0.0.1:8086",
]

[tasks.insert-readme]
clear = true
private = true
description = "copy the content of readme.md into *.rs comments (for the docs)"
script= ["..\\utils\\lmake_readme.exe"]

[tasks.cargo-doc]
clear = true
private = true
description = "call cargo doc"
command="cargo"
args=["doc","--no-deps","--document-private-items","--open"]

[tasks.doc-copy]
clear = true
private = true
description = "copy doc folder as docs (out of folder target), so it can be git comitted"
script = [
    "xcopy target\\doc docs /e /i /y /s ",
]

