# mem4_game/mem4/Makefile.toml
# https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo build development"
    clear = true
    dependencies = [
        "build-dev",
        "post-build",
    ]

    [tasks.release]
    description = "cargo build release"
    clear = true
    dependencies = [
        "build-release",
        "post-build",
    ]

    [tasks.doc]
    description = "call cargo doc"
    command="cargo"
    args=["doc","--no-deps","--document-private-items","--open"]

    #TODO: add a command to copy the text from readme.md inside lib.rs
    #a placeholder could be [include readme.md]
    #if some parts of readme are not desired maybe signal them with some indoc connand.
    #markdown comments are like this [comment]: # (blabla)

# endregion

[tasks.build-dev]
clear = true
private = true
command = "wasm-pack"
args = ["build", "--target", "web","--dev"]

[tasks.build-release]
clear = true
private = true
command = "wasm-pack"
args = ["build","--target", "web","--release"]

[tasks.post-build]
clear = true
private = true
windows_alias = "windows_post-build"

[tasks.windows_post-build]
clear = true
private = true
script = [
    "start chrome http://127.0.0.1:8086", 
    #"start \"firefox\" \"C:\\Program Files\\Mozilla Firefox\\firefox.exe\" 127.0.0.1:8086",
    "basic-http-server -a 127.0.0.1:8086",
]
